language: node_js
sudo: false
dist: trusty
services:
  - postgresql
cache:
  bundler: true
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - oAuth2
script:
  - npm run lint
  - npm run test
  - npm run test:cy
addons:
  postgresql: '9.4'
