language: node_js
sudo: false
dist: trusty
services:
  - postgresql
install:
  - npm ci
cache:
  bundler: true
  directories:
    - ~/.npm
    - ~/.cache
branches:
  only:
    - master
    - oAuth2
env:
  - TEST_SUITE=lint
  - TEST_SUITE=test
  - TEST_SUITE=test:cy

script:
  - 'npm run $TEST_SUITE'

addons:
  postgresql: '9.4'
