language: node_js
sudo: false
dist: trusty
services:
  - postgresql
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
  - oAuth2
script: 
  - npm run test
  - npm run lint
addons:
  postgresql: "9.4"
