version: "3"
services:

  database:
    image: postgres:9.6
    volumes:
      - ./tools/postgres-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hejmdal
