version: '3'
services:
  database:
    image: docker-dbc.artifacts.dbccloud.dk/dbc-postgres-14:latest
    environment:
      - POSTGRES_DB=hejmdal
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
