version: '3'
services:
  database:
    ports:
      - "5432:5432"
    image: postgres:9.6
    environment:
      POSTGRES_DB: hejmdal
  web:
    image: '${IMAGE:-hejmdal}:${TAG:-latest}'
    env_file: ./docker/env.docker
    depends_on:
      - database
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; node src/main.js'

  e2e:
    image: docker.dbc.dk/cypress:latest
    volumes:
      - './e2e:/app/e2e'
    depends_on:
      - web
    # note: inside e2e container, the network allows accessing
    # "web" host under name "web"
    # so "curl http://web" would return whatever the webserver
    # in the "web" container is cooking
    # see https://docs.docker.com/compose/networking/
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: bash -c 'sleep 10; npm run cy'

networks:
  default:
    ipam:
      config:
        - subnet: 12.0.0.0/16
